---
title: "Distributions"
output: word_document
---

```{r setup & library, include=F, message=F, warning=F}
#Load RData file 
load("./.RData")

#Do not show code chunks in the knitted document
knitr::opts_chunk$set(echo=F, warning=F, message=F)

#Declare vector of required packages
packages <- c("tidyverse", "readr")

#Load function to check whether required packages are installed & load required packages
source("./functions/check_required_packages.R")
check_required_packages(packages)
lapply(packages, require, character.only=T)

#Clean up
rm(packages)

##DATA##
data <- haven::read_spss("./data/dataE_clear5 2209.sav") %>% dplyr::select(CASE, sexdrive2, CSBD, PPCS_6, meffort, socialanx, lon, mvalue, attr)
```

# violin (and Bar) Plots of All Motivational Risk Factors for the Entire Sample

```{r violin plots}
#create long data frame for plotting, including only the relevant variables
plotd_all <- data %>% select(CASE, sexdrive2, CSBD, PPCS_6, meffort, socialanx, lon, mvalue, attr) %>% pivot_longer(cols=sexdrive2:attr, names_to="var", values_to="score")
#call on function
source("./functions/flat_violin.R")
#plot
ggplot(plotd_all %>% filter(var!="attr"), aes(x=as.factor(var), y=score, fill=var)) +
  geom_flat_violin(scale="width") +
  scale_fill_grey(start=.5, end=.9, aesthetics = "fill") +
  geom_dotplot(binaxis="y", dotsize=.04, stackdir="down", binwidth=.3, position=position_nudge(-.025)) +
  guides(fill="none") +
  scale_x_discrete(labels=c("CSBD"="Compulsive sex.", "lon"="Loneliness", "meffort"="Mating effort", "mvalue"="Mate value", "PPCS_6"="Probl. porn use", "sexdrive2"="Sex drive", "socialanx"="Social anxiety")) +
  labs(x="", y="Value") +
  theme_classic() +
  theme(axis.text.x=element_text(angle=45, hjust=1, size=10))
#plot attraction to children separately
ggplot(plotd_all %>% filter(var=="attr"), aes(x=score)) +
  geom_bar() +
  theme_classic() +
  labs(x="Attraction to children", y="Count")
```